# Generated by Django 3.1.2 on 2020-12-15 05:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='slider-one-title', max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, default='slider-one-subtitle', max_length=255, null=True)),
                ('button', models.CharField(blank=True, default='slider-one-button', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='btn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='Appointment', max_length=55, null=True)),
                ('color', models.CharField(blank=True, default='red', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('photo', models.ImageField(upload_to='media/influencer')),
                ('position', models.CharField(max_length=255, verbose_name='Ажлын байр')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Олны танил хүмүүс',
                'verbose_name_plural': 'Олны танил хүмүүс',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MonthSaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/salemonthproduct')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Зургын нэр')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Сарын онцлох бүтээгдэхүүн',
                'verbose_name_plural': 'Сарын онцлох бүтээгдэхүүн',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reclam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('video', models.CharField(max_length=255, verbose_name='Бичлэг')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Реклам',
                'verbose_name_plural': 'Реклам',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/saleproduct')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Зургын нэр')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Хямдралтай бүтээгдэхүүн',
                'verbose_name_plural': 'Хямдралтай бүтээгдэхүүн',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/servicephoto', verbose_name='Зураг')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Танилцуулга бүтээгдэхүүн',
                'verbose_name_plural': 'Танилцуулга бүтээгдхүүн',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='media/banner')),
                ('animationClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.animationclass')),
                ('btn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.btn')),
            ],
            options={
                'verbose_name': 'Баннер зураг',
                'verbose_name_plural': 'Баннер зураг',
            },
        ),
    ]
