# Generated by Django 3.1.2 on 2021-05-18 07:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='animationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='slider-one-title', max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, default='slider-one-title_en', max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, default='slider-one-subtitle', max_length=255, null=True)),
                ('subtitle_en', models.CharField(blank=True, default='slider-one-subtitle_en', max_length=255, null=True)),
                ('button', models.CharField(blank=True, default='slider-one-button', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Баннер туслах хэсэг',
                'verbose_name_plural': 'Баннер туслах хэсэг',
            },
        ),
        migrations.CreateModel(
            name='btn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='Appointment', max_length=55, null=True)),
                ('content_en', models.CharField(blank=True, default='Appointment_en', max_length=55, null=True)),
                ('color', models.CharField(blank=True, default='red', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Баннер туслах товч',
                'verbose_name_plural': 'Баннер туслах товч',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Илгээгчийн нэр')),
                ('name_en', models.CharField(max_length=255, verbose_name='Илгээгчийн нэр_en')),
                ('email', models.CharField(max_length=255, verbose_name='Имайл')),
                ('phone', models.CharField(max_length=100, verbose_name='Утасны дугаар')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Санал хүсэлт',
                'verbose_name_plural': 'Санал хүсэлт',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('image', models.ImageField(upload_to='media/influencer')),
                ('position', models.CharField(max_length=255, verbose_name='Ажлын байр')),
                ('position_en', models.CharField(max_length=255, verbose_name='Ажлын байр_en')),
                ('order', models.IntegerField(verbose_name='Эрэмблэх дараалал')),
                ('quote', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэлсэн үг (Шаарлаггүй талбар)')),
            ],
            options={
                'verbose_name': 'Олны танил хүмүүс',
                'verbose_name_plural': 'Олны танил хүмүүс',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='introductionOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Гарчиг')),
                ('title_en', models.CharField(max_length=1000, verbose_name='Гарчиг_en')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Тайлбар')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='Тайлбар_en')),
                ('photo', models.ImageField(upload_to='media/introductionOne', verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Танилцуулга бүтээгдэхүүн',
                'verbose_name_plural': 'Танилцуулга бүтээгдхүүн',
            },
        ),
        migrations.CreateModel(
            name='MonthSaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/salemonthproduct')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Зургын нэр')),
                ('order', models.IntegerField(verbose_name='Эрэмблэх дараалал')),
            ],
            options={
                'verbose_name': 'Сарын онцлох бүтээгдэхүүн',
                'verbose_name_plural': 'Сарын онцлох бүтээгдэхүүн',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reclam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('title_en', models.CharField(max_length=255, verbose_name='Гарчиг_en')),
                ('video', models.CharField(max_length=255, verbose_name='Бичлэг')),
                ('order', models.IntegerField(verbose_name='Эрэмблэх дараалал')),
            ],
            options={
                'verbose_name': 'Реклам',
                'verbose_name_plural': 'Реклам',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/monthly', verbose_name='Бүтээгдэхүүний зураг')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмблэх дараалал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Хямдралтай бүтээгдэхүүн',
                'verbose_name_plural': 'Хямдралтай бүтээгдэхүүн',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/monthly', verbose_name='Бүтээгдэхүүний зураг')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмблэх дараалал')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Сарын онцлох бүтээгдэхүүн',
                'verbose_name_plural': 'Сарын онцлох бүтээгдэхүүн',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='MonProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=255, verbose_name='Түлхүүр үг')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('product', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Онцлох бүтээгдэхүүнүүд',
                'verbose_name_plural': 'Онцлох бүтээгдэхүүнүүд',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('subTitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='media/banner', verbose_name='Зураг')),
                ('animationClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.animationclass')),
                ('btn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.btn')),
            ],
            options={
                'verbose_name': 'Баннер зураг',
                'verbose_name_plural': 'Баннер зураг',
            },
        ),
    ]
