# Generated by Django 3.1.2 on 2020-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201228_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/monthly')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сарын онцлох бүтээгдэхүүн',
                'verbose_name_plural': 'Сарын онцлох бүтээгдэхүүн',
                'ordering': ['-order'],
            },
        ),
    ]
