# Generated by Django 3.1.2 on 2020-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_monthlyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='saleproduct',
            name='picture',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/monthly'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
