# Generated by Django 3.1.2 on 2020-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201230_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='influencer',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
