# Generated by Django 3.1.2 on 2021-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201230_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Илгээгчийн нэр')),
                ('email', models.CharField(max_length=255, verbose_name='Имайл')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='influencer',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэлсэн үг'),
        ),
    ]
