# Generated by Django 3.1.2 on 2021-01-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210103_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['id'], 'verbose_name': 'Санал хүсэлт', 'verbose_name_plural': 'Санал хүсэлт'},
        ),
    ]
