# Generated by Django 3.1.2 on 2021-01-21 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210104_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animationclass',
            options={'verbose_name': 'Баннер туслах хэсэг', 'verbose_name_plural': 'Баннер туслах хэсэг'},
        ),
        migrations.AlterModelOptions(
            name='btn',
            options={'verbose_name': 'Баннер туслах товч', 'verbose_name_plural': 'Баннер туслах товч'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/banner', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='order',
            field=models.IntegerField(verbose_name='Эрэмблэх дараалал'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэлсэн үг (Шаарлаггүй талбар)'),
        ),
        migrations.AlterField(
            model_name='introductionone',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='introductionone',
            name='photo',
            field=models.ImageField(upload_to='media/introductionOne', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='introductionone',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='image',
            field=models.ImageField(upload_to='media/monthly', verbose_name='Бүтээгдэхүүний зураг'),
        ),
        migrations.AlterField(
            model_name='monthlyproduct',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Эрэмблэх дараалал'),
        ),
        migrations.AlterField(
            model_name='monthsaleproduct',
            name='order',
            field=models.IntegerField(verbose_name='Эрэмблэх дараалал'),
        ),
        migrations.AlterField(
            model_name='reclam',
            name='order',
            field=models.IntegerField(verbose_name='Эрэмблэх дараалал'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/monthly', verbose_name='Бүтээгдэхүүний зураг'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Эрэмблэх дараалал'),
        ),
    ]
