# Generated by Django 3.1.2 on 2020-12-15 07:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('description', models.CharField(max_length=500, verbose_name='Тайлбар')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(default='Админ', max_length=55, verbose_name='Оруулсан админ')),
                ('category', models.CharField(choices=[('ОМ', 'Онцлох мэдээ'), ('ЗМ', 'Зурган мэдээ'), ('БА', 'Бие арчилгаа'), ('МД', 'Мэдээ')], default='МД', max_length=255, verbose_name='Ангилал')),
                ('tags', models.CharField(choices=[('TR', 'tricks'), ('MU', 'make up')], default='TR', max_length=255, verbose_name='Шошго')),
                ('publicDate', models.DateTimeField(auto_now_add=True)),
                ('thumbImage', models.ImageField(upload_to='media/blog/thumbimage')),
                ('coverImage', models.ImageField(upload_to='media/blog/coverimage')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
