# Generated by Django 3.1.2 on 2021-05-18 07:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('title_en', models.CharField(max_length=255, verbose_name='Гарчиг_en')),
                ('description', models.CharField(max_length=500, verbose_name='Тайлбар')),
                ('description_en', models.CharField(max_length=500, verbose_name='Тайлбар_en')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(default='Админ', max_length=55, verbose_name='Оруулсан админ')),
                ('category', models.CharField(choices=[('Онцлох мэдээ', 'Онцлох мэдээ'), ('Зурган мэдээ', 'Зурган мэдээ'), ('Бие арчилгаа', 'Бие арчилгаа'), ('Мэдээ', 'Мэдээ')], default='МД', max_length=255, verbose_name='Ангилал')),
                ('category_en', models.CharField(choices=[('ontsloh News', 'ontsloh News'), ('Pic News', 'Pic News'), ('Body', 'Body'), ('News', 'News')], default='МД', max_length=255, verbose_name='Ангилал_en')),
                ('tags', models.CharField(choices=[('TR', 'tricks'), ('MU', 'make up')], default='TR', max_length=255, verbose_name='Шошго')),
                ('publicDate', models.DateTimeField(auto_now_add=True)),
                ('thumbImage', models.ImageField(upload_to='media/blog/thumbimage')),
                ('coverImage', models.ImageField(upload_to='media/blog/coverimage')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Мэдээ',
                'verbose_name_plural': 'Мэдээ',
                'ordering': ['-id'],
            },
        ),
    ]
