# Generated by Django 3.1.2 on 2021-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name': 'Мэдээ', 'verbose_name_plural': 'Мэдээ'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Онцлох мэдээ', 'Онцлох мэдээ'), ('Зурган мэдээ', 'Зурган мэдээ'), ('Бие арчилгаа', 'Бие арчилгаа'), ('Мэдээ', 'Мэдээ')], default='МД', max_length=255, verbose_name='Ангилал'),
        ),
    ]
