# Generated by Django 3.1.2 on 2020-10-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('АРЬС АРЧИЛГАА', 'Арьс арчилгаа'), ('ХЯМДРАЛТАЙ', 'Хямдралтай'), ('ҮС АРЧИЛГАА', 'Үс арчилгаа')], default='', max_length=550)),
                ('name', models.CharField(max_length=50)),
                ('rate', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('discount', models.CharField(default='0', max_length=255)),
                ('brand', models.CharField(choices=[('БИОГЕН', 'Биоген'), ('БИОМОН', 'Биомон'), ('БИОДЕРМ', 'Биодерм')], default='', max_length=550)),
                ('point', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('thumbimage', models.ImageField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
