# Generated by Django 3.1.2 on 2020-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('БИОГЕН', 'Биоген'), ('БИОМОН', 'Биомон'), ('БИОДЕРМ', 'Биодерм'), ('АЛОЕ', 'Алое'), ('САНИТАС', 'Санитас')], default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('АРЬС АРЧИЛГАА', 'Арьс арчилгаа'), ('ХЯМДРАЛТАЙ', 'Хямдралтай'), ('ҮС АРЧИЛГАА', 'Үс арчилгаа'), ('БИЕ АРЧИЛГАА', 'Бие арчилгаа'), ('ГАР АРЧИЛГАА', 'Гар арчилгаа'), ('САНИТАС АРИУТГАГЧ', 'Санитас ариутгагч'), ('ХҮҮХЭД', 'Хүүхэд'), ('МОЙЛ ОРГАНИК', 'Мойл органик'), ('МОЙЛ СПА', 'Мойл спа')], default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
