# Generated by Django 3.1.2 on 2021-05-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210518_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ангилал', 'verbose_name_plural': 'Ангилал'},
        ),
    ]
