# Generated by Django 3.1.2 on 2021-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210518_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=550, verbose_name='Ангилалын нэр'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=550, verbose_name='Ангилалын нэр_en'),
        ),
    ]
