# Generated by Django 3.1.2 on 2021-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210121_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_to_emonos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имонос линк'),
        ),
    ]
